  <div class="pageInt">
<div class="topTools error">

</div>

<header>
<h2>Erreur</h2>

</header>

<article>
   <p style="margin-top:50px; text-align:center"> <strong><?php echo $this->message ?></strong><br /><br />
    
    <a href="mailto:web@agencetexto.com?subject=Erreur sur <?php echo $_SERVER["HTTP_HOST"]; ?>">Contacter l'administrateur du site</a> ou <a href="accueil.html">retour &agrave; l'accueil</a></p>

</article>

</div>
  




