<?php  echo $this->docType(); ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
 </head>
<body bgcolor="#880038">
    
   
<div style="font-family:Arial, Verdana; position: relative; display: block; font-size:12px; color:#FFFFFF; width:960px; height: 884px; margin:auto;">
    
    <?php echo $this->layout()->content ?>
 
 </div>
</body>
</html>