<?php  echo $this->docType();

?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <?php  echo $this->headTitle()?>

  
  <?php echo $this->headLink()?>
  <script>DEFAULT_ADMIN_URL = "/admin/getjsondata/format/json";
  </script>
  
  
  <?php echo $this->headScript()?>
      <style>
        .x-border-layout-ct { background : #fff; }
    </style>
</head>
<body>
<div id="mainDiv">

 <?php echo $this->layout()->content ?>
 </div>
 
</body>
</html>